/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSlugRouteImport } from './routes/app.$slug'
import { Route as AppSlugRelatoriosRouteImport } from './routes/app.$slug.relatorios'
import { Route as AppSlugProntuarioRouteImport } from './routes/app.$slug.prontuario'
import { Route as AppSlugProcedimentosRouteImport } from './routes/app.$slug.procedimentos'
import { Route as AppSlugLeadsRouteImport } from './routes/app.$slug.leads'
import { Route as AppSlugFinanceiroRouteImport } from './routes/app.$slug.financeiro'
import { Route as AppSlugDashboardRouteImport } from './routes/app.$slug.dashboard'
import { Route as AppSlugConfiguracoesRouteImport } from './routes/app.$slug.configuracoes'
import { Route as AppSlugClientesRouteImport } from './routes/app.$slug.clientes'
import { Route as AppSlugAgendaRouteImport } from './routes/app.$slug.agenda'
import { Route as CSlugCaptacaoFormSlugRouteImport } from './routes/c.$slug.captacao.$formSlug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlugRoute = AppSlugRouteImport.update({
  id: '/app/$slug',
  path: '/app/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlugRelatoriosRoute = AppSlugRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugProntuarioRoute = AppSlugProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugProcedimentosRoute = AppSlugProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugLeadsRoute = AppSlugLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugFinanceiroRoute = AppSlugFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugDashboardRoute = AppSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugConfiguracoesRoute = AppSlugConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugClientesRoute = AppSlugClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugAgendaRoute = AppSlugAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppSlugRoute,
} as any)
const CSlugCaptacaoFormSlugRoute = CSlugCaptacaoFormSlugRouteImport.update({
  id: '/c/$slug/captacao/$formSlug',
  path: '/c/$slug/captacao/$formSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/$slug': typeof AppSlugRouteWithChildren
  '/app/$slug/agenda': typeof AppSlugAgendaRoute
  '/app/$slug/clientes': typeof AppSlugClientesRoute
  '/app/$slug/configuracoes': typeof AppSlugConfiguracoesRoute
  '/app/$slug/dashboard': typeof AppSlugDashboardRoute
  '/app/$slug/financeiro': typeof AppSlugFinanceiroRoute
  '/app/$slug/leads': typeof AppSlugLeadsRoute
  '/app/$slug/procedimentos': typeof AppSlugProcedimentosRoute
  '/app/$slug/prontuario': typeof AppSlugProntuarioRoute
  '/app/$slug/relatorios': typeof AppSlugRelatoriosRoute
  '/c/$slug/captacao/$formSlug': typeof CSlugCaptacaoFormSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/$slug': typeof AppSlugRouteWithChildren
  '/app/$slug/agenda': typeof AppSlugAgendaRoute
  '/app/$slug/clientes': typeof AppSlugClientesRoute
  '/app/$slug/configuracoes': typeof AppSlugConfiguracoesRoute
  '/app/$slug/dashboard': typeof AppSlugDashboardRoute
  '/app/$slug/financeiro': typeof AppSlugFinanceiroRoute
  '/app/$slug/leads': typeof AppSlugLeadsRoute
  '/app/$slug/procedimentos': typeof AppSlugProcedimentosRoute
  '/app/$slug/prontuario': typeof AppSlugProntuarioRoute
  '/app/$slug/relatorios': typeof AppSlugRelatoriosRoute
  '/c/$slug/captacao/$formSlug': typeof CSlugCaptacaoFormSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/$slug': typeof AppSlugRouteWithChildren
  '/app/$slug/agenda': typeof AppSlugAgendaRoute
  '/app/$slug/clientes': typeof AppSlugClientesRoute
  '/app/$slug/configuracoes': typeof AppSlugConfiguracoesRoute
  '/app/$slug/dashboard': typeof AppSlugDashboardRoute
  '/app/$slug/financeiro': typeof AppSlugFinanceiroRoute
  '/app/$slug/leads': typeof AppSlugLeadsRoute
  '/app/$slug/procedimentos': typeof AppSlugProcedimentosRoute
  '/app/$slug/prontuario': typeof AppSlugProntuarioRoute
  '/app/$slug/relatorios': typeof AppSlugRelatoriosRoute
  '/c/$slug/captacao/$formSlug': typeof CSlugCaptacaoFormSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/app/$slug'
    | '/app/$slug/agenda'
    | '/app/$slug/clientes'
    | '/app/$slug/configuracoes'
    | '/app/$slug/dashboard'
    | '/app/$slug/financeiro'
    | '/app/$slug/leads'
    | '/app/$slug/procedimentos'
    | '/app/$slug/prontuario'
    | '/app/$slug/relatorios'
    | '/c/$slug/captacao/$formSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/app/$slug'
    | '/app/$slug/agenda'
    | '/app/$slug/clientes'
    | '/app/$slug/configuracoes'
    | '/app/$slug/dashboard'
    | '/app/$slug/financeiro'
    | '/app/$slug/leads'
    | '/app/$slug/procedimentos'
    | '/app/$slug/prontuario'
    | '/app/$slug/relatorios'
    | '/c/$slug/captacao/$formSlug'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/login'
    | '/app/$slug'
    | '/app/$slug/agenda'
    | '/app/$slug/clientes'
    | '/app/$slug/configuracoes'
    | '/app/$slug/dashboard'
    | '/app/$slug/financeiro'
    | '/app/$slug/leads'
    | '/app/$slug/procedimentos'
    | '/app/$slug/prontuario'
    | '/app/$slug/relatorios'
    | '/c/$slug/captacao/$formSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  AppSlugRoute: typeof AppSlugRouteWithChildren
  CSlugCaptacaoFormSlugRoute: typeof CSlugCaptacaoFormSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$slug': {
      id: '/app/$slug'
      path: '/app/$slug'
      fullPath: '/app/$slug'
      preLoaderRoute: typeof AppSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$slug/relatorios': {
      id: '/app/$slug/relatorios'
      path: '/relatorios'
      fullPath: '/app/$slug/relatorios'
      preLoaderRoute: typeof AppSlugRelatoriosRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/prontuario': {
      id: '/app/$slug/prontuario'
      path: '/prontuario'
      fullPath: '/app/$slug/prontuario'
      preLoaderRoute: typeof AppSlugProntuarioRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/procedimentos': {
      id: '/app/$slug/procedimentos'
      path: '/procedimentos'
      fullPath: '/app/$slug/procedimentos'
      preLoaderRoute: typeof AppSlugProcedimentosRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/leads': {
      id: '/app/$slug/leads'
      path: '/leads'
      fullPath: '/app/$slug/leads'
      preLoaderRoute: typeof AppSlugLeadsRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/financeiro': {
      id: '/app/$slug/financeiro'
      path: '/financeiro'
      fullPath: '/app/$slug/financeiro'
      preLoaderRoute: typeof AppSlugFinanceiroRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/dashboard': {
      id: '/app/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/app/$slug/dashboard'
      preLoaderRoute: typeof AppSlugDashboardRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/configuracoes': {
      id: '/app/$slug/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/$slug/configuracoes'
      preLoaderRoute: typeof AppSlugConfiguracoesRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/clientes': {
      id: '/app/$slug/clientes'
      path: '/clientes'
      fullPath: '/app/$slug/clientes'
      preLoaderRoute: typeof AppSlugClientesRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/agenda': {
      id: '/app/$slug/agenda'
      path: '/agenda'
      fullPath: '/app/$slug/agenda'
      preLoaderRoute: typeof AppSlugAgendaRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/c/$slug/captacao/$formSlug': {
      id: '/c/$slug/captacao/$formSlug'
      path: '/c/$slug/captacao/$formSlug'
      fullPath: '/c/$slug/captacao/$formSlug'
      preLoaderRoute: typeof CSlugCaptacaoFormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppSlugRouteChildren {
  AppSlugAgendaRoute: typeof AppSlugAgendaRoute
  AppSlugClientesRoute: typeof AppSlugClientesRoute
  AppSlugConfiguracoesRoute: typeof AppSlugConfiguracoesRoute
  AppSlugDashboardRoute: typeof AppSlugDashboardRoute
  AppSlugFinanceiroRoute: typeof AppSlugFinanceiroRoute
  AppSlugLeadsRoute: typeof AppSlugLeadsRoute
  AppSlugProcedimentosRoute: typeof AppSlugProcedimentosRoute
  AppSlugProntuarioRoute: typeof AppSlugProntuarioRoute
  AppSlugRelatoriosRoute: typeof AppSlugRelatoriosRoute
}

const AppSlugRouteChildren: AppSlugRouteChildren = {
  AppSlugAgendaRoute: AppSlugAgendaRoute,
  AppSlugClientesRoute: AppSlugClientesRoute,
  AppSlugConfiguracoesRoute: AppSlugConfiguracoesRoute,
  AppSlugDashboardRoute: AppSlugDashboardRoute,
  AppSlugFinanceiroRoute: AppSlugFinanceiroRoute,
  AppSlugLeadsRoute: AppSlugLeadsRoute,
  AppSlugProcedimentosRoute: AppSlugProcedimentosRoute,
  AppSlugProntuarioRoute: AppSlugProntuarioRoute,
  AppSlugRelatoriosRoute: AppSlugRelatoriosRoute,
}

const AppSlugRouteWithChildren =
  AppSlugRoute._addFileChildren(AppSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  AppSlugRoute: AppSlugRouteWithChildren,
  CSlugCaptacaoFormSlugRoute: CSlugCaptacaoFormSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
